paths:
  /api/products/:
    get:
      summary: Obtain the list of products from the data base
      tags:
        - Products
      responses:
        "200":
          description: The list of products was obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error taking the list of products from the data base
    post:
      summary: Add a product to the list of products from the data base
      tags:
        - Products
        
  /api/products/{pid}:
    get:
      summary: Obtain a product from the data base by his Id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Id from the product searched
        schema:
          $type: String
      responses:
        "200":
          description: The product searched was found
        "500":
          description: Error searching the product
  /api/products/{pid}/product:
    post:
      summary: Add a product to the data base
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Id from the product to add to the data base
        schema:
          $type: String
      responses:
        "200":
          description: The product was added to the store
        "500":
          description: Error adding the product to the store

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id generated by MongoDB
        title:
          type: String
          description: Name of the product
        description:
          type: String
          description: Summary and caracteristics from the product
        thumbnail:
          type: String
          description: Thumbnail
        price:
          type: Number
          description: Price of the product in the store
        code:
          type: String
          description: Product's code in the store to identify it
        stock:
          type: Number
          description: Cuantity of the product which is abailable to be sold
        category:
          type: String
          description: Category of the product
        owner:
          type: String
          description: Information about who created the product in the store
      example:
        _id: Object_id("653934576d4ed1cd0ef8271c")
        title: TestProduct
        description: TestDescription
        thumbnail: TestImage
        price: 100
        status: true
        code: TestCode
        stock: 0
        category: CategoryA
        owner: Premium
